<?php

namespace Mr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository {
    public function orderedList() {
        return $this->createQueryBuilder('t')
                    ->orderBy('t.number', 'asc')
                    ->getQuery()
                    ->getResult();
    }
}
