<?php

namespace Mr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTeamRepository extends EntityRepository
{
}
