<?php

namespace Mr\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository {
    /**
     * Returns the last $limit messages into given language.
     *
     * @param string $language The current language
     * @param int    $limit    The limit of results
     * @return Message[]
     */
    public function getLast($language, $limit) {
        return $this->createQueryBuilder('m')
                    ->where('m.language = :language')
                    ->setParameter('language', $language)
                    ->setFirstResult(0)
                    ->setMaxResults($limit)
                    ->getQuery()
                    ->getResult();
    }
}
